# gen_zip_regions.py
# Generates a full Illinois ZIP->region map from the U.S. Census 2020
# ZCTA->County file and writes it to backend/services/zip_regions_data.py.
#
# Regions: chicago, suburban_cook, collar, illinois (matches routing.py).
# Re-run when ZIP assignments change (rare):
#   python scripts/gen_zip_regions.py
#   python scripts/validate_zip_counties.py  # sanity-check after

from __future__ import annotations

from collections import Counter
from pathlib import Path

import requests

CENSUS_URL = ("https://www2.census.gov/geo/docs/maps-data/data/rel2020/"
              "zcta520/tab20_zcta520_county20_natl.txt")
OUT = Path(__file__).resolve().parents[1] / "backend/services/zip_regions_data.py"

COOK   = "17031"
COLLAR = {"17043", "17097", "17197", "17089", "17111", "17093"}  # DuPage/Lake/Will/Kane/McHenry/Kendall


def is_chicago_zip(z: str) -> bool:
    n = int(z)
    return 60601 <= n <= 60661 or n in (60666, 60707)


def main() -> None:
    lines = requests.get(CENSUS_URL, timeout=90).text.splitlines()

    # Find the dominant IL county (largest land-area overlap) for each ZCTA.
    best: dict[str, tuple[int, str]] = {}
    for line in lines[1:]:
        f = line.split("|")
        zcta, cgeoid = f[1], f[9]
        if not zcta or not cgeoid.startswith("17"):
            continue
        try:
            area = int(f[16] or 0)
        except ValueError:
            area = 0
        if zcta not in best or area > best[zcta][0]:
            best[zcta] = (area, cgeoid)

    region = {}
    for z, (_, county) in best.items():
        if county == COOK:
            region[z] = "chicago" if is_chicago_zip(z) else "suburban_cook"
        elif county in COLLAR:
            region[z] = "collar"
        else:
            region[z] = "illinois"

    counts = Counter(region.values())
    body = ["# AUTO-GENERATED by scripts/gen_zip_regions.py -- do not edit by hand.",
            "# Full Illinois ZIP->region map from the U.S. Census 2020 ZCTA->County file.",
            f"# {len(region)} ZIPs: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())),
            "", "ZIP_REGION = {"]
    for z in sorted(region):
        body.append(f'    "{z}": "{region[z]}",')
    body.append("}")
    OUT.write_text("\n".join(body) + "\n")

    print(f"wrote {OUT} -- {len(region)} ZIPs")
    for k, v in sorted(counts.items()):
        print(f"  {k:<14} {v}")


if __name__ == "__main__":
    main()